/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as KilnRouteImport } from './routes/kiln'
import { Route as LanternRouteImport } from './routes/lantern'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const KilnRoute = KilnRouteImport.update({
  id: '/kiln',
  path: '/kiln',
  getParentRoute: () => rootRouteImport,
} as any)
const LanternRoute = LanternRouteImport.update({
  id: '/lantern',
  path: '/lantern',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/kiln': typeof KilnRoute
  '/lantern': typeof LanternRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/kiln': typeof KilnRoute
  '/lantern': typeof LanternRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/kiln': typeof KilnRoute
  '/lantern': typeof LanternRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blueprint' | '/kiln' | '/lantern'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blueprint' | '/kiln' | '/lantern'
  id: '__root__' | '/' | '/blueprint' | '/kiln' | '/lantern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlueprintRoute: typeof BlueprintRoute
  KilnRoute: typeof KilnRoute
  LanternRoute: typeof LanternRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiln': {
      id: '/kiln'
      path: '/kiln'
      fullPath: '/kiln'
      preLoaderRoute: typeof KilnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lantern': {
      id: '/lantern'
      path: '/lantern'
      fullPath: '/lantern'
      preLoaderRoute: typeof LanternRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlueprintRoute: BlueprintRoute,
  KilnRoute: KilnRoute,
  LanternRoute: LanternRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
